### ISSUE TITLE
Sov incorrectly renders outputs which are rotated

### ISSUE THREAD

**Issue by twitchyliquid64** [milgra/sov#6] opened 2022-04-26 18:42 UTC
![image](https://user-images.githubusercontent.com/6328589/165369710-d5b46c89-aa7e-4d0e-9917-014783495170.png)

See workspace 2: This is actually a very-wide monitor that has been rotated in sway using `transform 90`.

**Comment by primalmotion** [comment] 2022-04-27 20:39
I have a similar issue with a monitor coinfigured with negative offset:

```
~ % swaymsg -t get_outputs
Output eDP-1 'Chimei Innolux Corporation 0x1415 0x00000000' (focused)
  Current mode: 1920x1080 @ 60.001 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1: main
  Max render time: off
  Adaptive sync: disabled

Output DP-2 'Dell Inc. DELL U3419W GF2W5T2'
  Current mode: 3440x1440 @ 59.973 Hz
  Position: -760,-1440
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2: stack
  Max render time: off
  Adaptive sync: disabled
```

![screenshot-2022-04-27-13:37:32](https://user-images.githubusercontent.com/208711/165626949-127dba7f-0f7d-4717-9378-90745455534c.png)

**Comment by twitchyliquid64** [comment] 2022-04-27 22:48
Unrelated to sov, but I've encountered a ton of weird issues with negative positions so i would recommend you shift them all positive regardless.

**Comment by primalmotion** [comment] 2022-04-27 22:52
There are known issue with xwayland yes. But as I edited my comment, negative or not, it does not matter. The issue appears when I plug my monitor, even if I reset the positionning to default

**Comment by milgra** [comment] 2022-04-28 11:55
Thank you for the report, I try to reproduce it with a rotated second monitor.

**Comment by milgra** [comment] 2022-04-29 20:08
I tried it, I will modify sov to support multiple outputs and that will solve the issue.

**Comment by milgra** [comment] 2022-05-12 07:41
Fixed in v0.7, please check if it works correctly.

**Comment by primalmotion** [comment] 2022-05-12 18:42
it does :) thanks!

There's something weird though: my main screen has currently 5 workspaces and the second one only one. sov correctly shows the good workspace on the good screen. However the second screen shows 5 slots while I would have expected only one (see screenshot I'm probably being unclear :) )

![screenshot-2022-05-12-11:40:20](https://user-images.githubusercontent.com/208711/168145917-aa53c41c-4d94-4913-bf66-15f2af17e33d.png)
![screenshot-2022-05-12-11:40:26](https://user-images.githubusercontent.com/208711/168145983-f8b90e88-2954-41b6-b35e-9bac00f5aadf.png)

Not sure if this is a bug or a feature though :)

**Comment by milgra** [comment] 2022-05-13 09:42
yes, this is the expected behaviour, sov always shows all the columns defined in the config because it was simpler to implement :) thank you!

**Closed by milgra** 2022-05-13 09:42 UTC

**Comment by primalmotion** [comment] 2022-05-13 18:28
then everything is perfect :) Thanks!
