### ISSUE TITLE
Font Rendering is pixelated, unaliased

### ISSUE THREAD

**Issue by zzggbb** [milgra/sov#3] opened 2022-04-26 04:02 UTC
example of `sov` font rendering:

![example of `sov` font rendering](https://user-images.githubusercontent.com/4823914/165218588-acfb5c66-4d8d-446c-92f3-763cbc183724.png)

example of `termite` (a terminal emulator) font rendering:

![example of `termite` rendering](https://user-images.githubusercontent.com/4823914/165218635-3b7713b7-d9ef-4a68-9c4a-01f922f03bac.png)

**Comment by milgra** [comment] 2022-04-26 07:28
Hi, I think you have to pick a pre-defined size for this font, for example Terminus-TTF works with 14,16,18,20,22 pixel sizes, any other size causes the same pixelation for me also. If the problem still exists you should try a differenct face of this font.

**Comment by milgra** [comment] 2022-04-26 15:39
I tried it on my machine, I also have pixelated fonts for non-monospace fonts, I think I know where the problem is.

**Comment by twitchyliquid64** [comment] 2022-04-26 18:40
I'll note i ran into this with the default configuration file also.

**Comment by ferdinandschober** [comment] 2022-04-27 09:16
Terminus is a bitmap font so I don't think there is a proper workaround other than setting the correct font size

**Comment by milgra** [comment] 2022-04-28 12:27
Fixed in https://github.com/milgra/sov/releases/tag/0.62

**Closed by milgra** 2022-04-28 12:27 UTC
